# -*- coding: utf-8 -*-
"""app_ingles17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0He2F3dhO5IgdfbrWo-cS0qMK7VuSZq
"""

# -*- coding: utf-8 -*-

import streamlit as st
import random
import matplotlib.pyplot as plt
import pandas as pd
import io
import numpy as np
import scipy.io.wavfile as wavfile
import tempfile
import os
import time

# --- Importações de módulos locais ---
# Certifique-se de que 'data_exercises1.py' e 'pronunciation_phrases.py'
# estejam na mesma pasta que este arquivo.
from data_exercises1 import all_exercises_data, grammar_tips
# !!! Você precisa ter um arquivo 'pronunciation_phrases.py' no mesmo diretório !!!
# Se você não tem, crie-o com a variável pronunciation_phrases_data
# Caso contrário, comente ou remova a linha abaixo
from pronunciation_phrases import pronunciation_phrases_data

# --- Importações de bibliotecas instaladas ---
from gtts import gTTS # Para Text-to-Speech
from streamlit_webrtc import webrtc_streamer, AudioProcessorBase, WebRtcMode
import av # Necessário para streamlit-webrtc

# --- Configuração da página do Streamlit ---
# !!! ATENÇÃO: set_page_config DEVE SER A PRIMEIRA FUNÇÃO DO STREAMLIT CHAMADA !!!
st.set_page_config(page_title="App de Aprendizado de Inglês", layout="centered")

st.title("📚 App de Aprendizado de Inglês")

# --- Constantes ---
NUM_EXERCISES_PER_LEVEL = 15 # Número de exercícios por quiz

# --- Inicialização do estado da sessão ---
# Inicializa o nível atual se não estiver definido
if 'current_level' not in st.session_state:
    st.session_state.current_level = "Básico" # Nível padrão

# Inicializa o tipo de exercício padrão
if 'exercise_type' not in st.session_state:
    st.session_state.exercise_type = "Completar Frases" # Tipo padrão

# Inicializa o estado do quiz
if 'quiz_started' not in st.session_state:
    st.session_state.quiz_started = False
if 'current_question_index' not in st.session_state:
    st.session_state.current_question_index = 0
if 'score' not in st.session_state:
    st.session_state.score = 0
if 'answers' not in st.session_state:
    st.session_state.answers = []
if 'feedback' not in st.session_state:
    st.session_state.feedback = []
if 'show_results' not in st.session_state:
    st.session_state.show_results = False
if 'quiz_exercises' not in st.session_state:
    st.session_state.quiz_exercises = []
if 'selected_exercise_type' not in st.session_state:
    st.session_state.selected_exercise_type = None

# Inicializa o estado da página
if 'page' not in st.session_state:
    st.session_state.page = 'home'

# --- Inicialização do estado de pronúncia ---
if 'pronunciation_state' not in st.session_state:
    st.session_state.pronunciation_state = {
        'current_phrase_index': 0,
        'user_audio_data1': None, # Armazenar o caminho para o arquivo de áudio gravado
    }
# Adiciona o estado para a instância do AudioProcessor (para persistência da gravação)
if 'webrtc_audio_processor_instance' not in st.session_state:
    st.session_state['webrtc_audio_processor_instance'] = None

# --- Funções auxiliares ---

def play_audio(text, lang='en', filename="temp_audio.mp3"):
    """Gera e reproduz áudio a partir de texto usando gTTS."""
    try:
        tts = gTTS(text=text, lang=lang, slow=False)
        tts.save(filename)
        audio_file = open(filename, 'rb')
        audio_bytes = audio_file.read()
        st.audio(audio_bytes, format='audio/mp3')
        audio_file.close()
        os.remove(filename) # Limpa o arquivo temporário
    except Exception as e:
        st.error(f"Erro ao gerar ou reproduzir áudio: {e}")

def get_random_exercises(level, exercise_type, num_exercises=NUM_EXERCISES_PER_LEVEL):
    """Seleciona um número fixo de exercícios aleatórios para o quiz."""
    if level not in all_exercises_data:
        st.error(f"Erro: Nível '{level}' não encontrado nos dados dos exercícios.")
        return []
    if exercise_type not in all_exercises_data[level]:
        st.error(f"Erro: Tipo de exercício '{exercise_type}' não encontrado para o nível '{level}'.")
        return []

    available_exercises = all_exercises_data[level][exercise_type]
    if len(available_exercises) < num_exercises:
        st.warning(f"Atenção: Não há {num_exercises} exercícios disponíveis para o nível '{level}' e tipo '{exercise_type}'. Usando todos os {len(available_exercises)} exercícios disponíveis.")
        return random.sample(available_exercises, len(available_exercises))
    return random.sample(available_exercises, num_exercises)

def reset_quiz_state():
    """Reseta o estado do quiz para iniciar um novo."""
    st.session_state.quiz_started = False
    st.session_state.current_question_index = 0
    st.session_state.score = 0
    st.session_state.answers = []
    st.session_state.feedback = []
    st.session_state.show_results = False
    st.session_state.quiz_exercises = []
    st.session_state.selected_exercise_type = None

def start_new_quiz():
    """Inicia um novo quiz com base no nível e tipo selecionados."""
    # Garante que o nível selecionado existe
    if st.session_state.current_level not in all_exercises_data:
        st.error(f"Não há exercícios válidos disponíveis para o nível '{st.session_state.current_level}'. Por favor, verifique a estrutura de 'data_exercises1.py' para este nível.")
        st.warning("Por favor, selecione um nível com exercícios disponíveis ou verifique o arquivo 'data_exercises1.py'.")
        return

    # Garante que o tipo de exercício selecionado existe para o nível
    if st.session_state.exercise_type not in all_exercises_data[st.session_state.current_level]:
        st.error(f"Não há exercícios do tipo '{st.session_state.exercise_type}' disponíveis para o nível '{st.session_state.current_level}'.")
        st.warning("Por favor, selecione um tipo de exercício válido ou verifique o arquivo 'data_exercises1.py'.")
        return

    st.session_state.quiz_exercises = get_random_exercises(st.session_state.current_level, st.session_state.exercise_type)

    if not st.session_state.quiz_exercises:
        st.error("Não foi possível carregar os exercícios para o quiz. Por favor, tente novamente.")
        return

    st.session_state.quiz_started = True
    st.session_state.current_question_index = 0
    st.session_state.score = 0
    st.session_state.answers = [""] * len(st.session_state.quiz_exercises) # Inicializa com strings vazias
    st.session_state.feedback = [""] * len(st.session_state.quiz_exercises) # Inicializa feedback vazio
    st.session_state.show_results = False
    st.session_state.selected_exercise_type = st.session_state.exercise_type # Salva o tipo selecionado para o quiz atual

def check_answer(user_answer, correct_answer, question_index, exercise_type):
    """Verifica a resposta do usuário e atualiza o estado do quiz."""
    is_correct = False
    feedback_text = ""

    if exercise_type == "Completar Frases":
        # Para completar frases, a comparação é case-insensitive
        if user_answer.strip().lower() == correct_answer.strip().lower():
            is_correct = True
            feedback_text = "✅ Correto!"
        else:
            feedback_text = f"❌ Incorreto. A resposta correta era: **{correct_answer}**"
    elif exercise_type == "Múltipla Escolha":
        # Para múltipla escolha, a comparação é exata (opções já são strings normalizadas)
        if user_answer == correct_answer:
            is_correct = True
            feedback_text = "✅ Correto!"
        else:
            feedback_text = f"❌ Incorreto. A resposta correta era: **{correct_answer}**"

    if is_correct:
        st.session_state.score += 1

    st.session_state.answers[question_index] = user_answer # Salva a resposta do usuário
    st.session_state.feedback[question_index] = feedback_text # Salva o feedback
    st.session_state.current_question_index += 1 # Avança para a próxima pergunta

    # Verifica se o quiz terminou
    if st.session_state.current_question_index >= len(st.session_state.quiz_exercises):
        st.session_state.show_results = True

def init_pronunciation_state():
    """Inicializa o estado para o treino de pronúncia."""
    st.session_state.pronunciation_state = {
        'current_phrase_index': 0,
        'user_audio_data1': None,
    }
    # Zera também a instância do AudioProcessor quando a página é inicializada
    st.session_state['webrtc_audio_processor_instance'] = None


# --- Sidebar ---
with st.sidebar:
    st.header("Navegação")
    if st.button("🏠 Início", key="nav_home"):
        st.session_state.page = 'home'
        reset_quiz_state()
        init_pronunciation_state()
        st.rerun()

    if st.button("📚 Quiz de Gramática", key="nav_quiz"):
        st.session_state.page = 'quiz'
        reset_quiz_state() # Garante um estado limpo ao ir para o quiz
        init_pronunciation_state() # Garante que a gravação não "misture" estados
        st.rerun()

    if st.button("🗣️ Treino de Pronúncia", key="nav_pronunciation"):
        st.session_state.page = 'pronunciation'
        init_pronunciation_state() # Garante um estado limpo ao ir para pronúncia
        st.rerun()

    st.markdown("---")
    st.header("Configurações do Quiz")

    # Seleção de Nível
    level_options = list(all_exercises_data.keys()) # Pega as chaves ("Básico", "Intermediário", "Avançado")
    st.session_state.current_level = st.sidebar.selectbox(
        "Selecione o Nível:",
        level_options,
        index=level_options.index(st.session_state.current_level) if st.session_state.current_level in level_options else 0
    )

    # Seleção do Tipo de Exercício
    # Primeiro, garanta que o nível selecionado tem tipos de exercício
    if st.session_state.current_level in all_exercises_data:
        exercise_type_options = list(all_exercises_data[st.session_state.current_level].keys())
    else:
        exercise_type_options = ["Nenhum disponível"] # Fallback se o nível não for encontrado

    st.session_state.exercise_type = st.sidebar.selectbox(
        "Selecione o Tipo de Exercício:",
        exercise_type_options,
        index=exercise_type_options.index(st.session_state.exercise_type) if st.session_state.exercise_type in exercise_type_options else 0
    )

    if st.sidebar.button("🔄 Iniciar Novo Quiz com Estas Configurações"):
        st.session_state.page = 'quiz' # Garante que a página é a do quiz
        start_new_quiz()
        st.rerun()

    st.markdown("---")
    st.header("Recursos Gramaticais")
    for topic, tip in grammar_tips.items():
        with st.sidebar.expander(f"📖 {topic}"):
            st.write(tip)

# --- Lógica principal para o aplicativo ---
if st.session_state.page == 'home':
    st.write("Bem-vindo ao App de Aprendizado de Inglês! Aperfeiçoe suas habilidades com nossos quizzes e treinos de pronúncia.")
    st.markdown("---")
    st.write("Escolha uma seção para começar:")
    col1, col2 = st.columns(2)
    with col1:
        if st.button("📚 Iniciar Quiz de Gramática", use_container_width=True):
            st.session_state.page = 'quiz'
            start_new_quiz()
            st.rerun()
    with col2:
        if st.button("🗣️ Treino de Pronúncia", use_container_width=True):
            st.session_state.page = 'pronunciation'
            init_pronunciation_state()
            st.rerun()
    st.markdown("---")
    st.header("Dicas de Estudo")
    st.info("""
    * **Consistência é Chave:** Estude um pouco todos os dias.
    * **Pratique a Escuta:** Ouça músicas, podcasts e assista filmes em inglês.
    * **Fale em Voz Alta:** Use o treino de pronúncia para se sentir mais confortável.
    * **Revise Regularmente:** Volte aos tópicos que você achou difíceis.
    """)

elif st.session_state.page == 'quiz':
    st.header(f"Quiz de Gramática - Nível {st.session_state.current_level}")
    st.subheader(f"Tipo: {st.session_state.selected_exercise_type or st.session_state.exercise_type}")

    if not st.session_state.quiz_started:
        st.info("Clique em 'Iniciar Novo Quiz' na barra lateral para começar.")
    else:
        # Exibir a pergunta atual
        if not st.session_state.show_results:
            current_question_index = st.session_state.current_question_index
            if current_question_index < len(st.session_state.quiz_exercises):
                current_exercise = st.session_state.quiz_exercises[current_question_index]

                st.write(f"**Pergunta {current_question_index + 1} de {len(st.session_state.quiz_exercises)}**")

                # --- Determinar qual chave usar para a pergunta ---
                question_text = ""
                if st.session_state.selected_exercise_type == "Completar Frases":
                    question_text = current_exercise['frase_incompleta']
                elif st.session_state.selected_exercise_type == "Múltipla Escolha":
                    question_text = current_exercise['pergunta']
                else:
                    st.error("Tipo de exercício desconhecido. Não é possível exibir a pergunta.")
                    question_text = "Erro ao carregar a pergunta."

                st.write(f"**Frase:** \"{question_text}\"") # Usar a variável `question_text`

                # Botão de áudio para a frase
                if st.button(f"🔊 Ouvir Frase {current_question_index + 1}"):
                    play_audio(question_text) # O áudio também deve usar `question_text`

                if st.session_state.selected_exercise_type == "Completar Frases":
                    user_input = st.text_input("Sua resposta:", key=f"q_{current_question_index}")
                    if st.button("Verificar Resposta", key=f"check_{current_question_index}"):
                        check_answer(user_input, current_exercise['resposta_correta'], current_question_index, "Completar Frases")
                        st.rerun() # Recarrega a página para exibir o feedback e a próxima pergunta
                elif st.session_state.selected_exercise_type == "Múltipla Escolha":
                    # Certifica-se de que as opções são uma lista válida
                    options = current_exercise.get('opcoes', [])
                    selected_option = st.radio("Selecione a resposta:", options, key=f"q_{current_question_index}")
                    if st.button("Verificar Resposta", key=f"check_{current_question_index}"):
                        check_answer(selected_option, current_exercise['resposta_correta'], current_question_index, "Múltipla Escolha")
                        st.rerun() # Recarrega a página para exibir o feedback e a próxima pergunta
            else:
                st.session_state.show_results = True # Deve ter sido setado antes, mas garante

        # Exibir resultados finais ou feedback da última pergunta
        if st.session_state.show_results:
            st.subheader("Resultados do Quiz!")
            st.write(f"Você acertou **{st.session_state.score}** de **{len(st.session_state.quiz_exercises)}** perguntas.")

            # Gráfico de desempenho
            labels = ['Corretas', 'Incorretas']
            sizes = [st.session_state.score, len(st.session_state.quiz_exercises) - st.session_state.score]
            colors = ['#4CAF50', '#F44336'] # Verde para corretas, Vermelho para incorretas
            explode = (0.1, 0) # explode 1st slice

            fig1, ax1 = plt.subplots()
            ax1.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%',
                    shadow=True, startangle=90)
            ax1.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
            st.pyplot(fig1)

            st.markdown("---")
            st.subheader("Revisão de Suas Respostas:")
            for i, exercise in enumerate(st.session_state.quiz_exercises):
                col_q, col_a, col_f = st.columns([0.6, 0.3, 0.2])
                with col_q:
                    # --- Exibir a pergunta correta na revisão ---
                    display_question_text_review = ""
                    if st.session_state.selected_exercise_type == "Completar Frases":
                        display_question_text_review = exercise['frase_incompleta'].replace('___', '___' if st.session_state.answers[i] == '' else f'**{st.session_state.answers[i]}**')
                    elif st.session_state.selected_exercise_type == "Múltipla Escolha":
                        display_question_text_review = exercise['pergunta']
                    st.write(f"**Pergunta {i+1}:** {display_question_text_review}")

                with col_a:
                    st.write(f"**Sua Resposta:** {st.session_state.answers[i]}")
                with col_f:
                    st.write(st.session_state.feedback[i])
                st.markdown("---")

            if st.button("Reiniciar Quiz", key="reset_results_quiz"):
                reset_quiz_state()
                st.rerun()

        elif st.session_state.quiz_started and st.session_state.current_question_index == len(st.session_state.quiz_exercises):
            # Se todas as perguntas foram respondidas mas show_results ainda é False (caso raro), garanta que ele exiba
            st.session_state.show_results = True
            st.rerun()


elif st.session_state.page == 'pronunciation':
    st.header("🗣️ Treino de Pronúncia")
    st.write("Grave sua voz e compare sua pronúncia com a do aplicativo!")

    # Seleciona a frase atual para treino
    if 'current_phrase_index' not in st.session_state.pronunciation_state:
        st.session_state.pronunciation_state['current_phrase_index'] = 0

    current_phrase_index = st.session_state.pronunciation_state['current_phrase_index']
    phrases = pronunciation_phrases_data # Assume que esta variável existe em pronunciation_phrases.py

    if not phrases:
        st.error("Não há frases disponíveis para treino de pronúncia. Verifique 'pronunciation_phrases.py'.")
        if st.button("Voltar ao Início"):
            st.session_state.page = 'home'
            st.rerun()
        st.stop() # Para a execução se não há frases

    if current_phrase_index >= len(phrases):
        st.success("Você completou todas as frases de treino de pronúncia!")
        st.session_state.pronunciation_state['current_phrase_index'] = 0 # Reinicia para a primeira frase
        if st.button("Reiniciar Treino de Pronúncia"):
            init_pronunciation_state()
            st.rerun()
        st.stop()

    # --- Acessar a frase em inglês do dicionário ---
    current_phrase_dict = phrases[current_phrase_index]
    phrase_to_display_and_speak = current_phrase_dict.get('english_phrase', 'Frase não encontrada')

    st.subheader(f"Frase {current_phrase_index + 1} de {len(phrases)}:")
    st.markdown(f"## **\"{phrase_to_display_and_speak}\"**")

    # Botão para ouvir a frase original
    if st.button("🔊 Ouvir a frase", key="play_original_phrase"):
        play_audio(phrase_to_display_and_speak)

    st.markdown("---")
    st.subheader("Grave sua pronúncia:")

    class AudioRecorder(AudioProcessorBase):
        def __init__(self) -> None:
            self.audio_frames = []
            st.write("DEBUG: AudioRecorder inicializado.") # DEBUG

        def recv(self, frame: av.AudioFrame) -> av.AudioFrame:
            st.write(f"DEBUG: Frame de áudio recebida. Contagem de frames: {len(self.audio_frames)}") # DEBUG
            self.audio_frames.append(frame)
            return frame

        def _save_audio(self):
            st.write("DEBUG: Função _save_audio chamada.") # DEBUG
            if self.audio_frames:
                st.write(f"DEBUG: Salvando {len(self.audio_frames)} frames de áudio.") # DEBUG
                try:
                    audio_data = np.concatenate([f.to_ndarray(format="s16", layout="mono") for f in self.audio_frames])
                    st.write(f"DEBUG: Dados de audio - shape: {audio_data.shape}, dtype: {audio_data.dtype}") # DEBUG

                    # Cria um arquivo temporário com prefixo para fácil identificação
                    with tempfile.NamedTemporaryFile(delete=False, suffix=".wav", prefix="recorded_audio_") as tmpfile:
                        file_path = tmpfile.name
                        wavfile.write(file_path, 44100, audio_data)
                        st.session_state.pronunciation_state['user_audio_data1'] = file_path
                        st.write(f"DEBUG: Áudio salvo em: {file_path}") # DEBUG
                        self.audio_frames = [] # Limpa os frames após salvar
                        st.write("DEBUG: Frames de áudio limpas.") # DEBUG

                        # Adiciona um pequeno atraso para o sistema de arquivos processar
                        # Isso pode ajudar em casos de race condition
                        time.sleep(0.1)

                except Exception as e:
                    st.error(f"DEBUG: Erro durante _save_audio: {e}") # DEBUG
            else:
                st.write("DEBUG: _save_audio chamada, mas sem frames para salvar.") # DEBUG

    # Configuração do webrtc_streamer
    webrtc_ctx = webrtc_streamer(
        key="audio_recorder_webrtc", # Chave estática
        mode=WebRtcMode.SENDONLY,
        audio_processor_factory=AudioRecorder,
        media_stream_constraints={"video": False, "audio": True},
        async_processing=True,
    )

    # Armazene a instância do audio_processor no session_state para persistência
    if webrtc_ctx.audio_processor:
        st.session_state['webrtc_audio_processor_instance'] = webrtc_ctx.audio_processor

    # Lógica de salvamento e exibição
    if 'webrtc_audio_processor_instance' in st.session_state and st.session_state['webrtc_audio_processor_instance'] is not None:
        current_processor = st.session_state['webrtc_audio_processor_instance']

        if webrtc_ctx.state.playing:
            st.info("Gravando... Fale a frase acima.")
            st.write("DEBUG: Estado WebRTC: Gravando (Playing)") # DEBUG
        else:
            st.write("DEBUG: Estado WebRTC: Não Gravando (Not Playing)") # DEBUG
            # Verifica se há frames coletadas na instância persistente e se o processamento parou
            # Adicionado uma verificação se user_audio_data1 já foi preenchido para evitar repetição
            if current_processor.audio_frames and len(current_processor.audio_frames) > 0 and st.session_state.pronunciation_state['user_audio_data1'] is None:
                st.warning("Áudio detectado e gravação parada. Salvando gravação...")
                current_processor._save_audio() # Chama o método de salvamento
                # Importante: Limpar a instância persistente APÓS salvar, para que não tente salvar de novo na próxima rerun
                st.session_state['webrtc_audio_processor_instance'] = None
                st.rerun() # Recarrega a página para exibir o áudio salvo
            elif st.session_state.pronunciation_state['user_audio_data1'] is None:
                st.info("Pressione 'Iniciar' no widget acima para começar a gravar.")
    else:
        # Mensagem inicial se o processador ainda não foi inicializado pelo webrtc_streamer
        st.info("Aguardando inicialização do microfone. Pressione 'Iniciar' para começar.")

    # Área para reprodução e exclusão da gravação do usuário
    # Esta seção agora é executada independentemente da lógica de gravação para garantir que o áudio seja sempre exibido se o caminho estiver lá
    if 'user_audio_data1' in st.session_state.pronunciation_state and st.session_state.pronunciation_state['user_audio_data1']:
        audio_file_path = st.session_state.pronunciation_state['user_audio_data1']
        if os.path.exists(audio_file_path):
            st.markdown("---")
            st.write("Sua gravação:")
            # Tenta carregar o áudio. Se falhar, tenta novamente com um pequeno atraso.
            try:
                st.audio(audio_file_path, format='audio/wav', key="user_recorded_audio")
            except Exception as e:
                st.warning(f"Erro ao carregar áudio para reprodução: {e}. Tentando novamente em 0.5 segundos...")
                time.sleep(0.5) # Pequeno atraso antes de tentar novamente
                st.rerun() # Recarrega para tentar carregar o áudio novamente

            if st.button("🗑️ Excluir esta gravação"):
                os.remove(audio_file_path)
                st.session_state.pronunciation_state['user_audio_data1'] = None
                # Limpa a instância do processador também ao excluir
                st.session_state['webrtc_audio_processor_instance'] = None
                st.success("Gravação excluída.")
                st.rerun()
        else:
            st.warning(f"O arquivo de áudio gravado não foi encontrado: {audio_file_path}. O estado será resetado.") # DEBUG para verificar caminho
            st.session_state.pronunciation_state['user_audio_data1'] = None # Limpa o estado se o arquivo sumiu
            st.rerun() # Recarrega para limpar a exibição
    else:
        pass # Não há áudio para exibir, então não faz nada aqui

    st.markdown("---")

    # --- Botão para a Próxima Frase ---
    if st.button("➡️ Próxima Frase para Treino"):
        if st.session_state.pronunciation_state['user_audio_data1']:
            try:
                os.remove(st.session_state.pronunciation_state['user_audio_data1'])
            except OSError:
                pass
        st.session_state.pronunciation_state['user_audio_data1'] = None
        st.session_state['webrtc_audio_processor_instance'] = None # Garante que o processador é resetado para a próxima frase
        st.session_state.pronunciation_state['current_phrase_index'] += 1
        st.session_state.pronunciation_state['current_phrase_index'] = st.session_state.pronunciation_state['current_phrase_index'] % len(phrases)
        st.rerun()

    # --- Botão para Voltar à Frase Anterior ---
    if st.button("⬅️ Frase Anterior"):
        if st.session_state.pronunciation_state['user_audio_data1']:
            try:
                os.remove(st.session_state.pronunciation_state['user_audio_data1'])
            except OSError:
                pass
        st.session_state.pronunciation_state['user_audio_data1'] = None
        st.session_state['webrtc_audio_processor_instance'] = None # Garante que o processador é resetado para a anterior
        st.session_state.pronunciation_state['current_phrase_index'] -= 1
        if st.session_state.pronunciation_state['current_phrase_index'] < 0:
            st.session_state.pronunciation_state['current_phrase_index'] = len(phrases) - 1
        st.rerun()