# -*- coding: utf-8 -*-
"""app_ingles9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMhRPgocb2UnXTUutPbQJqUEOjbkZ7Gj
"""

import streamlit as st
import random
from data_exercises import all_exercises_data, grammar_tips

st.set_page_config(page_title="App de Aprendizado de Inglês", layout="centered")

st.title("📚 App de Aprendizado de Inglês")

# Sidebar para seleção de níveis
st.sidebar.header("Configurações do Exercício")
level = st.sidebar.selectbox("Selecione o Nível:",
                           options=list(all_exercises_data.keys()),
                           index=0)  # Garante que sempre tenha um valor padrão

# Verificação de segurança dos níveis disponíveis
if level not in all_exercises_data:
    st.error("Nível selecionado não existe nos dados!")
    st.stop()

# Função corrigida sem experimental_rerun
def display_fill_in_the_blanks_exercise(level):
    try:
        exercises = all_exercises_data[level]["Completar Frases"]
    except KeyError as e:
        st.error(f"Erro na estrutura de dados: {str(e)}")
        st.stop()

    if not exercises:
        st.warning(f"Não há exercícios para o nível '{level}' ainda.")
        return

    # Inicialização segura do session_state
    if 'exercise_data' not in st.session_state or st.session_state.get('current_level') != level:
        st.session_state.exercise_data = {
            'current_level': level,
            'index': 0,
            'shuffled': random.sample(exercises, len(exercises)),
            'user_answer': '',
            'feedback': '',
            'show_answer': False
        }

    current = st.session_state.exercise_data['shuffled'][st.session_state.exercise_data['index']]

    # Exibição do nível e tipo de gramática
    st.subheader(f"Nível: {level} - Completar Frases")
    st.markdown(f"**Tipo de Gramática:** 🎯 *{current['tipo']}*")
    st.write("---")

    # Widget de resposta com chave única
    user_input = st.text_input(
        "Sua resposta:",
        value=st.session_state.exercise_data['user_answer'],
        key=f"resposta_{st.session_state.exercise_data['index']}"
    )

    col1, col2 = st.columns(2)
    with col1:
        if st.button("✅ Verificar"):
            if user_input.strip().lower() == current["resposta_correta"].lower():
                st.session_state.exercise_data['feedback'] = "✅ Correto!"
            else:
                st.session_state.exercise_data['feedback'] = f"❌ Incorreto. Resposta correta: **{current['resposta_correta']}**"
            st.session_state.exercise_data['show_answer'] = True

    with col2:
        if st.button("⏭️ Próximo"):
            # Atualização segura do estado
            st.session_state.exercise_data.update({
                'index': (st.session_state.exercise_data['index'] + 1) % len(st.session_state.exercise_data['shuffled']),
                'user_answer': '',
                'feedback': '',
                'show_answer': False
            })

    # Exibição do feedback
    if st.session_state.exercise_data['show_answer']:
        st.markdown(f"**Feedback:** {st.session_state.exercise_data['feedback']}")

    # Contador de progresso
    st.write("---")
    st.caption(f"Progresso: {st.session_state.exercise_data['index'] + 1}/{len(st.session_state.exercise_data['shuffled'])} exercícios")

# Execução principal
display_fill_in_the_blanks_exercise(level)