# -*- coding: utf-8 -*-
"""app_ingles10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mAai_7nQ4ktJuIsyMrVBLsO5n3M_WZ5T
"""

import streamlit as st
import random
from data_exercises import all_exercises_data, grammar_tips

st.set_page_config(page_title="App de Aprendizado de Inglês", layout="centered")

st.title("📚 App de Aprendizado de Inglês")

# --- Funções de gerenciamento de estado ---
def _initialize_exercise_state(level, exercises):
    """Inicializa ou reinicializa o estado do exercício para um novo nível ou sessão."""
    st.session_state.exercise_data = {
        'current_level': level,
        'index': 0,
        'shuffled': random.sample(exercises, len(exercises)),
        'user_answer': '',
        'feedback': '',
        'show_answer': False,
        'show_tip': False # Novo estado para mostrar a dica
    }

def _next_exercise():
    """Avança para o próximo exercício."""
    current_index = st.session_state.exercise_data['index']
    total_exercises = len(st.session_state.exercise_data['shuffled'])

    st.session_state.exercise_data.update({
        'index': (current_index + 1) % total_exercises,
        'user_answer': '',
        'feedback': '',
        'show_answer': False,
        'show_tip': False # Reseta o estado da dica
    })

def _check_answer(user_input_val, correct_answer):
    """Verifica a resposta do usuário e atualiza o feedback."""
    if user_input_val.strip().lower() == correct_answer.lower():
        st.session_state.exercise_data['feedback'] = "✅ Correto!"
    else:
        st.session_state.exercise_data['feedback'] = f"❌ Incorreto. Resposta correta: **{correct_answer}**"
    st.session_state.exercise_data['show_answer'] = True
    st.session_state.exercise_data['show_tip'] = False # Esconde a dica se estava visível

def _show_grammar_tip(grammar_type):
    """Exibe a dica de gramática."""
    tip = grammar_tips.get(grammar_type, "Não há uma dica específica para este tipo de gramática.")
    st.session_state.exercise_data['feedback'] = f"**Dica sobre {grammar_type}:** {tip}"
    st.session_state.exercise_data['show_answer'] = True # Usamos o feedback para mostrar a dica, marcando como 'show_answer'
    st.session_state.exercise_data['show_tip'] = True # Indica que é uma dica


# Sidebar para seleção de níveis
st.sidebar.header("Configurações do Exercício")
level = st.sidebar.selectbox("Selecione o Nível:",
                             options=list(all_exercises_data.keys()),
                             index=0)

# Verificação de segurança dos níveis disponíveis
if level not in all_exercises_data:
    st.error("Nível selecionado não existe nos dados!")
    st.stop()

# Carrega os exercícios para o nível selecionado
try:
    exercises = all_exercises_data[level]["Completar Frases"]
except KeyError as e:
    st.error(f"Erro na estrutura de dados: {str(e)}")
    st.stop()

if not exercises:
    st.warning(f"Não há exercícios para o nível '{level}' ainda.")
    st.stop() # Parar aqui se não houver exercícios

# --- Lógica principal do Streamlit ---

# Inicializa o estado se for a primeira vez ou se o nível mudou
if 'exercise_data' not in st.session_state or st.session_state.exercise_data['current_level'] != level:
    _initialize_exercise_state(level, exercises)

current_exercise = st.session_state.exercise_data['shuffled'][st.session_state.exercise_data['index']]

# Exibição do nível e tipo de gramática
st.subheader(f"Nível: {level} - Completar Frases")
st.markdown(f"**Tipo de Gramática:** 🎯 *{current_exercise['tipo']}*")
st.write("---")

# Exibição da frase do exercício
st.markdown(f"### Complete a frase:")
st.markdown(f"## **`{current_exercise['frase']}`**")

# Widget de resposta com chave única
# Importante: o valor padrão do text_input deve vir do session_state
user_input = st.text_input(
    "Sua resposta:",
    value=st.session_state.exercise_data['user_answer'],
    key=f"resposta_{st.session_state.exercise_data['index']}" # Chave única para cada exercício
)

# --- Botões de ação ---
col1, col2, col3 = st.columns(3)

with col1:
    # O botão 'Verificar' chama uma função que atualiza o feedback
    st.button("✅ Verificar", on_click=_check_answer, args=(user_input, current_exercise['resposta_correta']))

with col2:
    # O botão 'Próximo' chama uma função que avança o exercício
    st.button("⏭️ Próximo", on_click=_next_exercise)

with col3:
    # O botão 'Dica de Gramática' chama uma função que exibe a dica
    st.button("💡 Dica de Gramática", on_click=_show_grammar_tip, args=(current_exercise['tipo'],))

# --- Exibição de Feedback/Dica ---
# O feedback é exibido apenas se show_answer for True
if st.session_state.exercise_data['show_answer']:
    if st.session_state.exercise_data['show_tip']:
        # Se for uma dica, formatamos como info
        st.info(st.session_state.exercise_data['feedback'])
    else:
        # Caso contrário, é um feedback de verificação
        st.markdown(f"**Feedback:** {st.session_state.exercise_data['feedback']}")

# Contador de progresso
st.write("---")
st.caption(f"Progresso: {st.session_state.exercise_data['index'] + 1}/{len(st.session_state.exercise_data['shuffled'])} exercícios")