# -*- coding: utf-8 -*-
"""app_ingles17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxylZXZVkcfAyk3MVPiq4_UBSAgF1PHe
"""

# -*- coding: utf-8 -*-

import streamlit as st
import random
import matplotlib.pyplot as plt
import pandas as pd
import io
import numpy as np
import scipy.io.wavfile as wavfile
import tempfile
import os
import time

# --- Importações de módulos locais ---
# Certifique-se de que 'data_exercises.py1' e 'pronunciation_phrases.py'
# estejam na mesma pasta que este arquivo.
from data_exercises1 import all_exercises_data, grammar_tips
from pronunciation_phrases import pronunciation_phrases_data

# --- Importações de bibliotecas instaladas ---
from gtts import gTTS # Para Text-to-Speech
from streamlit_webrtc import webrtc_streamer, AudioProcessorBase, WebRtcMode

# --- Configuração da página do Streamlit ---
# !!! ATENÇÃO: set_page_config DEVE SER A PRIMEIRA FUNÇÃO DO STREAMLIT CHAMADA !!!
st.set_page_config(page_title="App de Aprendizado de Inglês", layout="centered")

st.title("📚 App de Aprendizado de Inglês")

# --- Constantes ---
NUM_EXERCISES_PER_LEVEL = 15 # Número de exercícios por quiz

# --- Dados para as referências de gramática (para os expanders da sidebar) ---
VERB_TO_BE_DATA = """
**Verbo To Be (Ser/Estar)**

**Presente Simples:**
* **I** am (Eu sou/estou)
* **You** are (Você é/está)
* **He** is (Ele é/está)
* **She** is (Ela é/está)
* **It** is (Ele/Ela é/está - para coisas/animais)
* **We** are (Nós somos/estamos)
* **You** are (Vocês são/estão)
* **They** are (Eles/Elas são/estão)

**Passado Simples:**
* **I** was (Eu era/estava)
* **You** were (Você era/estava)
* **He** was (Ele era/estava)
* **She** was (Ela era/estava)
* **It** was (Ele/Ela era/estava - para coisas/animais)
* **We** were (Nós éramos/estávamos)
* **You** were (Vocês eram/estavam)
* **They** were (Eles/Elas eram/estavam)

**Usos Comuns:**
* **Para identificar ou descrever:** I am a student. (Eu sou um estudante.)
* **Para falar sobre localização:** She is at home. (Ela está em casa.)
* **Para expressar idade:** He is 30 years old. (Ele tem 30 anos.)
* **Para falar sobre sentimentos/condições:** They are happy. (Eles estão felizes.)
"""

PRESENT_SIMPLE_DATA = """
**Presente Simples (Simple Present)**

**Formação:**
* **Verbos regulares:** Infinitivo (base form) para I, You, We, They.
    * Ex: I **play**, You **work**, We **study**, They **read**.
* **Para He, She, It (3ª pessoa do singular):** Adicione '-s', '-es' ou '-ies' ao final do verbo.
    * Verbos terminados em -s, -ss, -sh, -ch, -x, -o: adicione '-es'. Ex: go -> go**es**, wash -> wash**es**.
    * Verbos terminados em consoante + y: troque o 'y' por 'i' e adicione '-es'. Ex: study -> stud**ies**.
    * Outros: adicione '-s'. Ex: play -> play**s**, work -> work**s**.

**Usos:**
1.  **Hábitos e rotinas:** I **drink** coffee every morning. (Eu tomo café toda manhã.)
2.  **Fatos gerais e verdades:** The sun **risess** in the east. (O sol nasce no leste.)
3.  **Horários fixos (programas, transportes):** The train **leaves** at 7 PM. (O trem parte às 19h.)
4.  **Instruções ou direções:** First, you **add** water. (Primeiro, você adiciona água.)

**Palavras-chave (adverbios de frequência):**
* always (sempre)
* usually (geralmente)
* often (com frequência)
* sometimes (às vezes)
* rarely (raramente)
* never (nunca)
* every day/week/month (todo dia/semana/mês)
"""

PAST_SIMPLE_DATA = """
**Passado Simples (Simple Past)**

**Formação:**
* **Verbos Regulares:** Adicione '-ed', '-d' ou '-ied' ao final do verbo.
    * Verbos terminados em 'e': adicione '-d'. Ex: love -> lov**ed**.
    * Verbos terminados em consoante + y: troque 'y' por 'i' e adicione '-ed'. Ex: study -> stud**ied**.
    * Outros: adicione '-ed'. Ex: work -> work**ed**, play -> play**ed**.
    * (Consoante-vogal-consoante - CVC, duplique a última consoante e adicione '-ed'. Ex: stop -> stopp**ed**).
* **Verbos Irregulares:** Possuem formas próprias que devem ser memorizadas.
    * Ex: go -> **went**, eat -> **ate**, see -> **saw**, be -> **was/were**.

**Usos:**
1.  **Ações concluídas no passado em um tempo específico:** I **visited** Paris last year. (Eu visitei Paris no ano passado.)
2.  **Série de ações passadas:** She **woke up**, **had** breakfast, and **left** for work. (Ela acordou, tomou café e saiu para o trabalho.)
3.  **Duração no passado:** They **lived** in London for five years. (Eles viveram em Londres por cinco anos.)

**Palavras-chave:**
* yesterday (ontem)
* last night/week/month/year (ontem à noite/semana/mês/ano passada)
* ... ago (há ...)
* in 2005 (em 2005 - ano passado)
"""

FUTURE_SIMPLE_DATA = """
**Futuro Simples (Simple Future)**

**Formação:**
* **Com 'will':** Sujeito + **will** + Verbo (base form).
    * Ex: I **will study** tomorrow. (Eu estudarei amanhã.)
    * Usado para decisões espontâneas, previsões sem evidência forte, promessas.
* **Com 'be going to':** Sujeito + **(am/is/are) going to** + Verbo (base form).
    * Ex: She **is going to travel** next month. (Ela vai viajar no próximo mês.)
    * Usado para planos e intenções futuras, previsões com evidência forte.

**Usos:**
1.  **Previsões:** It **will rain** tomorrow. (Vai chover amanhã.) / Look at the clouds! It's **going to rain**. (Olhe as nuvens! Vai chover.)
2.  **Decisões espontâneas (will):** "I'm thirsty." "I **will get** you some water." (Estou com sede. Eu vou te pegar água.)
3.  **Planos e intenções (be going to):** We **are going to buy** a new car. (Nós vamos comprar um carro novo.)
4.  **Promessas (will):** I **will help** you. (Eu te ajudarei.)

**Palavras-chave:**
* tomorrow (amanhã)
* next week/month/year (próxima semana/mês/ano)
* soon (em breve)
* in the future (no futuro)
"""

# --- Inicialização do estado da sessão para EXERCÍCIOS ---
if 'exercise_data1' not in st.session_state:
    st.session_state.exercise_data1 = {
        'current_exercise_index': 0,
        'correct_count': 0,
        'incorrect_count': 0,
        'quiz_finished': False,
        'shuffled_exercises': [],
        'current_answered': False,
        'selected_option': None,
        'show_answer': False,
        'show_tip': False,
        'feedback': "", # Feedback para a resposta do exercício
        'tip_content': "" # Conteúdo da dica de gramática
    }

# --- Inicialização do estado da sessão para PRONÚNCIA ---
if 'pronunciation_state' not in st.session_state:
    st.session_state.pronunciation_state = {
        'current_phrase_index': 0,
        'user_audio_data1': None, # Caminho para o arquivo de áudio temporário do usuário
        'feedback': "" # Feedback para a pronúncia (futuro)
    }

# --- Sidebar (Seletor de Modo) ---
st.sidebar.header("Configurações")
app_mode = st.sidebar.radio("Escolha o Modo:", ["Exercícios", "Treino de Pronúncia"])

# --- Lógica do Modo "Exercícios" ---
if app_mode == "Exercícios":
    st.sidebar.header("Configurações do Exercício")
    level = st.sidebar.selectbox("Selecione o Nível:", options=list(all_exercises_data.keys()), index=0)

    # Função para embaralhar os exercícios (apenas uma vez por sessão/nível ou ao iniciar um novo quiz)
    def _initialize_exercises():
        # Apenas inicializa se os exercícios não foram carregados ou se o quiz anterior terminou
        if not st.session_state.exercise_data1['shuffled_exercises'] or \
           st.session_state.exercise_data1['quiz_finished']:

            # Use .get() para evitar KeyError se o nível não existir em all_exercises_data
            selected_exercises_for_level = all_exercises_data.get(level)

            # Verifica se selected_exercises_for_level é uma lista e não está vazia
            if isinstance(selected_exercises_for_level, list) and selected_exercises_for_level:
                random.shuffle(selected_exercises_for_level)
                # Garante que não tentará pegar mais exercícios do que o disponível
                st.session_state.exercise_data1['shuffled_exercises'] = selected_exercises_for_level[:NUM_EXERCISES_PER_LEVEL]
            else:
                # Se não for uma lista ou estiver vazia, define como lista vazia
                st.session_state.exercise_data1['shuffled_exercises'] = []
                st.warning(f"Não há exercícios válidos disponíveis para o nível '{level}'. Por favor, verifique a estrutura de 'data_exercises1.py' para este nível.")

            st.session_state.exercise_data1['current_exercise_index'] = 0
            st.session_state.exercise_data1['correct_count'] = 0
            st.session_state.exercise_data1['incorrect_count'] = 0
            st.session_state.exercise_data1['quiz_finished'] = False
            st.session_state.exercise_data1['current_answered'] = False
            st.session_state.exercise_data1['selected_option'] = None
            st.session_state.exercise_data1['show_answer'] = False
            st.session_state.exercise_data1['show_tip'] = False
            st.session_state.exercise_data1['feedback'] = ""
            st.session_state.exercise_data1['tip_content'] = "" # Limpar conteúdo da dica

    # Inicializa ou reinicia os exercícios quando o nível muda ou o quiz termina
    if st.sidebar.button("Novo Quiz", on_click=_initialize_exercises) or \
       not st.session_state.exercise_data1['shuffled_exercises']: # Inicia automaticamente se vazio
        _initialize_exercises()

    # --- Lógica para exibir exercícios ou mensagem de erro se não houver exercícios ---
    if not st.session_state.exercise_data1['shuffled_exercises']:
        st.info("Por favor, selecione um nível com exercícios disponíveis ou verifique o arquivo 'data_exercises1.py'.")
    elif st.session_state.exercise_data1['quiz_finished']:
        st.subheader("🎉 Quiz Concluído!")
        st.write(f"Você acertou {st.session_state.exercise_data1['correct_count']} de {NUM_EXERCISES_PER_LEVEL} exercícios.")
        st.write(f"Erros: {st.session_state.exercise_data1['incorrect_count']}")

        if st.session_state.exercise_data1['correct_count'] == NUM_EXERCISES_PER_LEVEL:
            st.balloons()
            st.success("Parabéns! Você acertou todos os exercícios!")
        elif st.session_state.exercise_data1['correct_count'] >= NUM_EXERCISES_PER_LEVEL * 0.7:
            st.info("Muito bom! Continue praticando para alcançar a perfeição.")
        else:
            st.warning("Continue praticando para melhorar seus resultados!")

    else: # Quiz ainda não terminou
        current_exercise_index = st.session_state.exercise_data1['current_exercise_index']
        current_exercise = st.session_state.exercise_data1['shuffled_exercises'][current_exercise_index]

        st.subheader(f"Exercício {current_exercise_index + 1} de {NUM_EXERCISES_PER_LEVEL}")
        st.markdown(f"**Complete a frase:**")
        st.markdown(f"## {current_exercise['frase_incompleta']}")

        # Exibe as opções como radio buttons
        selected_option = st.radio(
            "Selecione a resposta:",
            current_exercise['shuffled_options'],
            key=f"radio_{current_exercise_index}", # Garante um key único para cada exercício
            disabled=st.session_state.exercise_data1['current_answered'] # Desabilita após responder
        )

        # Armazena a opção selecionada no estado da sessão
        if selected_option is not None:
            st.session_state.exercise_data1['selected_option'] = selected_option


        col1, col2, col3 = st.columns(3)

        with col1:
            st.button(
                "✅ Verificar",
                on_click=lambda: _check_answer(current_exercise['resposta_correta']), # Usar lambda para passar o argumento
                disabled=st.session_state.exercise_data1['current_answered'] or st.session_state.exercise_data1['selected_option'] is None
            )

        with col2:
            st.button(
                "⏭️ Próximo",
                on_click=_next_exercise,
                disabled=not st.session_state.exercise_data1['current_answered']
            )

        with col3:
            st.button(
                "💡 Dica de Gramática",
                on_click=lambda: _show_grammar_tip(current_exercise['tipo']), # Usar lambda para passar o argumento
                disabled=st.session_state.exercise_data1['show_tip']
            )

        # --- Exibição de Feedback/Dica ---
        # Exibe o feedback da resposta
        if st.session_state.exercise_data1['show_answer'] and st.session_state.exercise_data1['feedback']:
            st.markdown(st.session_state.exercise_data1['feedback'])

        # Exibe a dica de gramática se 'show_tip' for True e houver conteúdo
        if st.session_state.exercise_data1['show_tip'] and st.session_state.exercise_data1['tip_content']:
            with st.expander(st.session_state.exercise_data1['feedback'] if st.session_state.exercise_data1['feedback'].startswith("💡") else "Ver Conteúdo da Dica", expanded=True):
                st.markdown(st.session_state.exercise_data1['tip_content'])


    # --- Sidebar: Resultados do Quiz (Gráfico de Pizza) ---
    st.sidebar.subheader("Resultados Atuais")
    total_answered = st.session_state.exercise_data1['correct_count'] + st.session_state.exercise_data1['incorrect_count']

    if total_answered > 0:
        correct_percentage = (st.session_state.exercise_data1['correct_count'] / total_answered) * 100
        incorrect_percentage = (st.session_state.exercise_data1['incorrect_count'] / total_answered) * 100

        labels = ['Corretas', 'Incorretas']
        sizes = [correct_percentage, incorrect_percentage]
        colors = ['#4CAF50', '#F44336'] # Verde para correto, Vermelho para incorreto

        # Diminuindo o gráfico de pizza (figsize)
        fig1, ax1 = plt.subplots(figsize=(3, 3)) # Reduzido de (4,4) para (3,3)
        ax1.pie(sizes, labels=labels, autopct='%1.1f%%', colors=colors, startangle=90)
        ax1.axis('equal') # Garante que o círculo seja desenhado corretamente
        st.sidebar.pyplot(fig1)

        st.sidebar.write(f"Total de exercícios respondidos: {total_answered}")
        st.sidebar.write(f"Acertos: {st.session_state.exercise_data1['correct_count']}")
        st.sidebar.write(f"Erros: {st.session_state.exercise_data1['incorrect_count']}")
    else:
        st.sidebar.info("Comece a resolver os exercícios para ver os resultados aqui!")


    st.sidebar.write("---") # Linha divisória para separar seções

    # --- Sidebar: Tabelas de Referência Rápida (Gramática) ---
    st.sidebar.header("Tabelas de Referência Rápida")

    with st.sidebar.expander("Verbo 'To Be'"):
        st.markdown(VERB_TO_BE_DATA)

    with st.sidebar.expander("Presente Simples"):
        st.markdown(PRESENT_SIMPLE_DATA)

    with st.sidebar.expander("Passado Simples"):
        st.markdown(PAST_SIMPLE_DATA)

    with st.sidebar.expander("Futuro Simples"):
        st.markdown(FUTURE_SIMPLE_DATA)

    st.sidebar.write("---") # Linha divisória final


# --- Lógica do Modo "Treino de Pronúncia" ---
elif app_mode == "Treino de Pronúncia":
    st.header("🗣️ Treino de Pronúncia")
    st.markdown("Ouça a frase, grave sua repetição e compare!")

    # Lógica para navegar entre as frases
    # Se chegarmos ao final da lista, podemos embaralhar ou reiniciar
    if st.session_state.pronunciation_state['current_phrase_index'] >= len(pronunciation_phrases_data):
        st.info("Você completou todas as frases para treino de pronúncia! Recomeçando com uma ordem aleatória.")
        random.shuffle(pronunciation_phrases_data) # Isso embaralha a lista global
        st.session_state.pronunciation_state['current_phrase_index'] = 0


    current_phrase_data1 = pronunciation_phrases_data[st.session_state.pronunciation_state['current_phrase_index']]

    st.markdown(f"**Frase para treino ({st.session_state.pronunciation_state['current_phrase_index'] + 1} de {len(pronunciation_phrases_data)}):**")
    st.markdown(f"### {current_phrase_data1['english_phrase']}")
    st.markdown(f"**Tradução:** _{current_phrase_data1['portuguese_translation']}_")

    # --- Botão para Ouvir a Frase Original ---
    if st.button("▶️ Ouvir Frase Original"):
        try:
            # Gerar o áudio usando gTTS
            tts = gTTS(text=current_phrase_data1['english_phrase'], lang='en', slow=False)
            fp = io.BytesIO()
            tts.save(fp)
            fp.seek(0) # Volta ao início do arquivo em memória
            st.audio(fp, format='audio/mp3', start_time=0)
        except Exception as e:
            st.error(f"Erro ao gerar áudio: {e}. Verifique sua conexão com a internet ou tente novamente.")


    st.markdown("---") # Divisor

    st.markdown("### 🎤 Grave sua Repetição")

    # --- Lógica de Gravação com Streamlit-WebRTC ---
    # Definir uma classe processadora de áudio para capturar os frames
    class AudioFrameProcessor(AudioProcessorBase):
        def __init__(self):
            self.frames = []
            self.start_time = None

        def recv(self, frame: np.ndarray) -> np.ndarray:
            if self.start_time is None:
                self.start_time = time.time()
            # frame é um array numpy (mono). Adicione uma cópia para evitar problemas de referência.
            self.frames.append(frame.copy())
            return frame # Retorna o frame para que o áudio possa ser reproduzido no feedback, se desejado

    # Cria ou reutiliza o componente webrtc_streamer
    webrtc_ctx = webrtc_streamer(
        key="speech_recorder_pronunciation",
        mode=WebRtcMode.SENDONLY, # Apenas envia áudio do navegador para o backend
        audio_processor_factory=AudioFrameProcessor,
        media_stream_constraints={"video": False, "audio": True},
        async_processing=True,
    )

    st.write("Clique em 'Iniciar' para começar a gravar. Fale a frase acima. Clique em 'Parar' para finalizar.")

    if webrtc_ctx.audio_processor:
        if webrtc_ctx.state.playing:
            st.warning("Gravando... Fale a frase agora. (Clique em 'Parar' no widget acima para terminar)")
            # Adicione um botão para parar a gravação explicitamente e processar
            # Este botão é útil caso o widget webrtc_streamer não seja imediatamente responsivo ao stop
            if st.button("⏸️ Parar Gravação e Processar Áudio"):
                # Captura os frames do processador
                audio_frames = webrtc_ctx.audio_processor.frames

                if audio_frames:
                    try:
                        # Concatena todos os frames de audio
                        all_frames = np.concatenate(audio_frames, axis=0)
                        sample_rate = 48000 # Taxa de amostragem padrão do WebRTC para áudio

                        # Cria um arquivo WAV temporário para o áudio do usuário
                        with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as tmp_file:
                            wavfile.write(tmp_file.name, sample_rate, all_frames)
                            user_audio_path = tmp_file.name

                        st.session_state.pronunciation_state['user_audio_data1'] = user_audio_path
                        st.success("Gravação concluída! Você pode ouvir sua repetição abaixo.")
                        st.audio(user_audio_path, format='audio/wav')

                        # Limpar os frames gravados para a próxima gravação
                        webrtc_ctx.audio_processor.frames = []
                        webrtc_ctx.audio_processor.start_time = None # Reseta o tempo de início
                        # Pequeno atraso para garantir que o estado do webrtc_streamer seja atualizado
                        time.sleep(1) # Ajuda a evitar conflitos de estado no Streamlit
                        st.rerun() # Recarrega para refletir o novo estado de gravação

                    except Exception as e:
                        st.error(f"Erro ao processar sua gravação: {e}")
                        st.session_state.pronunciation_state['user_audio_data1'] = None
                else:
                    st.warning("Nenhum áudio foi capturado. Certifique-se de ter permissão de microfone e que ele está ativo.")
        else: # webrtc_ctx.state.playing is False (não está gravando)
            if st.session_state.pronunciation_state['user_audio_data1']:
                st.markdown("---") # Divisor para separar a gravação da reprodução
                st.write("Sua gravação:")
                st.audio(st.session_state.pronunciation_state['user_audio_data1'], format='audio/wav')
                if st.button("🗑️ Excluir esta gravação"):
                    os.remove(st.session_state.pronunciation_state['user_audio_data1'])
                    st.session_state.pronunciation_state['user_audio_data1'] = None
                    st.success("Gravação excluída.")
                    st.rerun() # Recarrega a página para atualizar o estado
            else:
                st.info("Pronto para gravar! Clique em 'Iniciar' no widget acima para começar.")

    st.markdown("---") # Divisor

    # --- Botão para a Próxima Frase ---
    if st.button("➡️ Próxima Frase para Treino"):
        # Limpa o áudio do usuário e o feedback ao avançar
        if st.session_state.pronunciation_state['user_audio_data1']:
            try:
                os.remove(st.session_state.pronunciation_state['user_audio_data1'])
            except OSError:
                pass # Ignora se o arquivo já foi removido ou não existe
        st.session_state.pronunciation_state['user_audio_data1'] = None
        st.session_state.pronunciation_state['current_phrase_index'] += 1
        st.session_state.pronunciation_state['feedback'] = ""
        st.rerun() # Recarrega para exibir a próxima frase