# -*- coding: utf-8 -*-
"""app_ingles1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FE5k6L4J3P4XET2h8YxfreYVtoyHS2zE
"""

import pdfplumber

def extract_text_from_pdf(pdf_path):
    text = ""
    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages:
                text += page.extract_text() + "\n"
    except Exception as e:
        print(f"Erro ao extrair texto do PDF: {e}")
    return text

# Nome do arquivo PDF que você carregou
pdf_file_path = "apostila-01-basico.pdf"
basic_pdf_text = extract_text_from_pdf(pdf_file_path)

# Vamos imprimir as primeiras linhas para ter uma ideia do conteúdo
print("--- Primeiras 1000 caracteres do PDF ---")
print(basic_pdf_text[:1000])
print("\n--- Fim das Primeiras 1000 caracteres ---\n")