# -*- coding: utf-8 -*-
"""data_exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1set-xBcj-v4CKc4GjGghCGS3n0hApgWs
"""

# data_exercises.py (para manter os dados separados, se preferir)

basic_fill_in_the_blanks = [
    {"frase": "I ___ a student.", "resposta_correta": "am"},
    {"frase": "You ___ happy.", "resposta_correta": "are"},
    {"frase": "He ___ from Brazil.", "resposta_correta": "is"},
    {"frase": "She ___ my sister.", "resposta_correta": "is"},
    {"frase": "It ___ a cat.", "resposta_correta": "is"},
    {"frase": "We ___ friends.", "resposta_correta": "are"},
    {"frase": "They ___ teachers.", "resposta_correta": "are"},
    {"frase": "Hello, my name ___ John.", "resposta_correta": "is"},
    {"frase": "Where ___ you from?", "resposta_correta": "are"},
    {"frase": "How old ___ she?", "resposta_correta": "is"},
    {"frase": "I ___ eleven years old.", "resposta_correta": "am"},
    {"frase": "They ___ in the park.", "resposta_correta": "are"},
    {"frase": "She ___ a doctor.", "resposta_correta": "is"},
    {"frase": "We ___ friends.", "resposta_correta": "are"},
    {"frase": "It ___ a big dog.", "resposta_correta": "is"},
    {"frase": "They ___ playing soccer.", "resposta_correta": "are"},
    {"frase": "I ___ a new car.", "resposta_correta": "have"},
    {"frase": "He ___ a brother.", "resposta_correta": "has"},
    {"frase": "You ___ a good idea.", "resposta_correta": "have"},
    {"frase": "She ___ beautiful.", "resposta_correta": "is"},
    {"frase": "We ___ happy to see you.", "resposta_correta": "are"},
    {"frase": "The cat ___ on the table.", "resposta_correta": "is"},
    {"frase": "They ___ eating pizza.", "resposta_correta": "are"},
    {"frase": "I ___ read that book.", "resposta_correta": "can"},
    {"frase": "He ___ speak English well.", "resposta_correta": "can"},
    {"frase": "She ___ run fast.", "resposta_correta": "can"},
    {"frase": "We ___ go to the park.", "resposta_correta": "can"},
    {"frase": "It ___ rain tomorrow.", "resposta_correta": "might"},
    {"frase": "You ___ help me, please?", "resposta_correta": "can"},
    {"frase": "They ___ arrive soon.", "resposta_correta": "will"},
    {"frase": "I ___ go to bed early.", "resposta_correta": "should"},
    {"frase": "He ___ study for the test.", "resposta_correta": "should"},
    {"frase": "She ___ eat healthy food.", "resposta_correta": "should"},
    {"frase": "We ___ listen to the teacher.", "resposta_correta": "should"},
    {"frase": "You ___ close the door.", "resposta_correta": "must"},
    {"frase": "They ___ follow the rules.", "resposta_correta": "must"},
    {"frase": "I ___ like coffee.", "resposta_correta": "don't"},
    {"frase": "He ___ like milk.", "resposta_correta": "doesn't"},
    {"frase": "She ___ play tennis.", "resposta_correta": "doesn't"},
    {"frase": "We ___ have time.", "resposta_correta": "don't"},
    {"frase": "They ___ understand.", "resposta_correta": "don't"},
    {"frase": "I ___ from Brazil.", "resposta_correta": "am"},
    {"frase": "Where ___ you from?", "resposta_correta": "are"},
    {"frase": "What ___ your name?", "resposta_correta": "is"},
    {"frase": "How ___ you?", "resposta_correta": "are"},
    {"frase": "I ___ hungry.", "resposta_correta": "am"},
    {"frase": "He ___ thirsty.", "resposta_correta": "is"},
    {"frase": "She ___ tired.", "resposta_correta": "is"},
    {"frase": "We ___ busy.", "resposta_correta": "are"},
    {"frase": "They ___ happy.", "resposta_correta": "are"},
    {"frase": "It ___ cold outside.", "resposta_correta": "is"},
    {"frase": "I ___ a student.", "resposta_correta": "am"}
    {"frase": "I ___ to school every day.", "resposta_correta": "go"},
    {"frase": "He ___ TV in the evening.", "resposta_correta": "watches"},
    {"frase": "She ___ books.", "resposta_correta": "reads"},
    {"frase": "We ___ lunch at noon.", "resposta_correta": "eat"},
    {"frase": "They ___ English.", "resposta_correta": "speak"},
    {"frase": "The dog ___ fast.", "resposta_correta": "runs"},
    {"frase": "I ___ coffee for breakfast.", "resposta_correta": "drink"},
    {"frase": "He ___ to music.", "resposta_correta": "listens"},
    {"frase": "She ___ dinner at 7 PM.", "resposta_correta": "cooks"},
    {"frase": "We ___ a big house.", "resposta_correta": "have"},
    {"frase": "They ___ a cat.", "resposta_correta": "have"},
    {"frase": "The baby ___ a lot.", "resposta_correta": "sleeps"},
    {"frase": "I ___ up early.", "resposta_correta": "get"},
    {"frase": "He ___ dressed quickly.", "resposta_correta": "gets"},
    {"frase": "She ___ a shower.", "resposta_correta": "takes"},
    {"frase": "We ___ work at 9 AM.", "resposta_correta": "start"},
    {"frase": "They ___ home late.", "resposta_correta": "arrive"},
    {"frase": "The sun ___ in the east.", "resposta_correta": "rises"},
    {"frase": "The moon ___ at night.", "resposta_correta": "shines"},
    {"frase": "Birds ___ in the sky.", "resposta_correta": "fly"},
    {"frase": "Fish ___ in the water.", "resposta_correta": "swim"},
    {"frase": "Children ___ in the park.", "resposta_correta": "play"},
    {"frase": "Flowers ___ in spring.", "resposta_correta": "bloom"},
    {"frase": "I ___ a question.", "resposta_correta": "have"},
    {"frase": "Do you ___ any siblings?", "resposta_correta": "have"},
    {"frase": "Where ___ you live?", "resposta_correta": "do"},
    {"frase": "What ___ you do?", "resposta_correta": "do"},
    {"frase": "___ you like pizza?", "resposta_correta": "Do"},
    {"frase": "___ he work here?", "resposta_correta": "Does"},
    {"frase": "___ she speak French?", "resposta_correta": "Does"},
    {"frase": "I ___ not like spiders.", "resposta_correta": "do"},
    {"frase": "He ___ not eat meat.", "resposta_correta": "does"},
    {"frase": "She ___ not sing well.", "resposta_correta": "does"},
    {"frase": "We ___ not have much time.", "resposta_correta": "do"},
    {"frase": "They ___ not understand.", "resposta_correta": "do"},
    {"frase": "This ___ my book.", "resposta_correta": "is"},
    {"frase": "That ___ your car.", "resposta_correta": "is"},
    {"frase": "These ___ my keys.", "resposta_correta": "are"},
    {"frase": "Those ___ his shoes.", "resposta_correta": "are"},
    {"frase": "The apple ___ red.", "resposta_correta": "is"}

    ]

# Podemos adicionar uma estrutura maior como no plano original:
all_exercises_data = {
    "Básico": {
        "Completar Frases": basic_fill_in_the_blanks,
        "Perguntas e Respostas": [
            # Adicionar aqui no futuro
        ],
        "Textos Curtos": [
            # Adicionar aqui no futuro
        ]
    },
    "Intermediário": {
        "Completar Frases": [], # Preencher depois
        "Perguntas e Respostas": [],
        "Textos Curtos": []
    },
    "Avançado": {
        "Completar Frases": [], # Preencher depois
        "Perguntas e Respostas": [],
        "Textos Curtos": []
    }
}

